// Package docs GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/mainnet/GetBalance/{qaddress}": {
            "get": {
                "description": "GetBalance gRPC",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mainnet"
                ],
                "summary": "GetBalance for mainnet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "QRL address",
                        "name": "qaddress",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/mainnet/GetHeight": {
            "get": {
                "description": "GetHeight gRPC",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mainnet"
                ],
                "summary": "GetHeight for mainnet",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/mainnet/GetNodeState": {
            "get": {
                "description": "GetNodeState gRPC",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mainnet"
                ],
                "summary": "GetNodeState for mainnet",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/mainnet/GetStats": {
            "get": {
                "description": "GetStats gRPC",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "mainnet"
                ],
                "summary": "GetStats for Mainnet",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/testnet/GetBalance/{qaddress}": {
            "get": {
                "description": "GetBalance gRPC",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "testnet"
                ],
                "summary": "GetBalance for testnet",
                "parameters": [
                    {
                        "type": "string",
                        "description": "QRL address",
                        "name": "qaddress",
                        "in": "path"
                    }
                ],
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/testnet/GetHeight": {
            "get": {
                "description": "GetHeight gRPC",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "testnet"
                ],
                "summary": "GetHeight for testnet",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/testnet/GetNodeState": {
            "get": {
                "description": "GetNodeState gRPC",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "testnet"
                ],
                "summary": "GetNodeState for testnet",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        },
        "/testnet/GetStats": {
            "get": {
                "description": "GetStats gRPC",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "testnet"
                ],
                "summary": "GetStats for testnet",
                "responses": {
                    "200": {
                        "description": ""
                    }
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "/testnet",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
